name: blast_report
description: Generate HTML reports from BLAST results
keywords:
  - blast
  - genotype
  - report
  - html
input:
  - - meta:
        type: map
        description: |
          Groovy map containing sample information
          e.g. [ id:'test' ]
    - blast:
        type: file
        description: |
          Unfiltered blast results file
        pattern: "*.{txt}"
        ontologies:
          - edam: http://edamontology.org/format_2330 # TXT
    - fasta:
        type: file
        description: Fasta file containing scaffolds
        pattern: "*.{fasta,fa}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
output:
  blast_report:
    - - meta:
          type: map
          description: |
            Groovy map containing sample information
            e.g. [ id:'test' ]
      - "*.html":
          type: file
          description: Results report in HTML format
          pattern: "*.{html}"
          ontologies:
            - edam: http://edamontology.org/format_2331 # HTML
  reversed_contigs:
    - - meta:
          type: map
          description: |
            Groovy map containing sample information
            e.g. [ id:'test' ]
      - fasta:
          type: file
          description: Fasta file containing forward and reverse complement contigs
          pattern: "*.{fa}"
          ontologies:
            - edam: http://edamontology.org/format_1929 # FASTA
  genotype:
    - - meta:
          type: map
          description: |
            Groovy map containing sample information
            e.g. [ id:'test' ]
      - "*.csv":
          type: file
          description: Genotype results in CSV format
          pattern: "*.{csv}"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - "python --version 2>&1 | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
  versions_matplotlib:
    - - ${task.process}:
          type: string
          description: The name of the process
      - matplotlib:
          type: string
          description: The name of the tool
      - "python -c 'import matplotlib; print(matplotlib.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
  versions_seaborn:
    - - ${task.process}:
          type: string
          description: The name of the process
      - seaborn:
          type: string
          description: The name of the tool
      - "python -c 'import seaborn; print(seaborn.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
  versions_pandas:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pandas:
          type: string
          description: The name of the tool
      - "python -c 'import pandas; print(pandas.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
  versions_jinja2:
    - - ${task.process}:
          type: string
          description: The name of the process
      - jinja2:
          type: string
          description: The name of the tool
      - "python -c 'import jinja2; print(jinja2.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
  topics:
    versions:
      - - ${task.process}:
            type: string
            description: The name of the process
        - python:
            type: string
            description: The name of the tool
        - "python --version 2>&1 | sed 's/Python //g'":
            type: eval
            description: The expression to obtain the version of the tool
      - - ${task.process}:
            type: string
            description: The name of the process
        - matplotlib:
            type: string
            description: The name of the tool
        - "python -c 'import matplotlib; print(matplotlib.__version__)'":
            type: eval
            description: The expression to obtain the version of the tool
      - - ${task.process}:
            type: string
            description: The name of the process
        - seaborn:
            type: string
            description: The name of the tool
        - "python -c 'import seaborn; print(seaborn.__version__)'":
            type: eval
            description: The expression to obtain the version of the tool
      - - ${task.process}:
            type: string
            description: The name of the process
        - pandas:
            type: string
            description: The name of the tool
        - "python -c 'import pandas; print(pandas.__version__)'":
            type: eval
            description: The expression to obtain the version of the tool
      - - ${task.process}:
            type: string
            description: The name of the process
        - jinja2:
            type: string
            description: The name of the tool
        - "python -c 'import jinja2; print(jinja2.__version__)'":
            type: eval
            description: The expression to obtain the version of the tool
authors:
  - "@svarona"
  - "@AnnaNoren"
maintainers:
  - "@svarona"
  - "@AnnaNoren"
