lint:
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
    - assets/nf-core-viralrecon_logo_light.png
    - docs/images/nf-core-viralrecon_logo_light.png
    - docs/images/nf-core-viralrecon_logo_dark.png

  template_strings:
    - assets/hiv_template_report.html
    - assets/blast_report_template.html
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Patel H, Varona S and Monzon S
  description: Assembly and intrahost/low-frequency variant calling for viral samples
  force: false
  is_nfcore: true
  name: viralrecon
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 3.1.0dev
